spring.application.name=faculty-career-system
spring.datasource.url=jdbc:mysql://localhost:3306/career_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root3508
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
